#!/usr/bin/php
<?php
    $template = 'http://example.com/path/%s.jpg';
    for ($i = 1; $i < 37; $i++) {
        $page = file_get_contents(sprintf($template, $i));
        file_put_contents(sprintf('%02d.jpeg', $i), $page);
        echo ".";
    }
    echo "\nDone.\n";
