#!/bin/bash
PATCHEE="/usr/bin/gitk"

if [ ! -f "$PATCHEE" ];
then
	echo ERROR: "$PATCHEE" not found
	exit 2;
fi

sudo cat $PATCHEE | sed -e "s/bind . <F5> updatecommits$/bind . <F5> reloadcommits/g" > /tmp/gitk_tmp
sudo cp /tmp/gitk_tmp $PATCHEE

echo "Gitk patched"
exit 0
